name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: package.json
      - run: npm ci
      - run: npm run check-format
      - run: npm run build
      - run: npm run lint
      - run: npm run test

      - if: ${{ github.event_name == 'push' && github.ref_name == 'main' }}
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ap-northeast-1
      - if: ${{ github.event_name == 'push' && github.ref_name == 'main' }}
        working-directory: ./projects/admin/dist
        run: |
          zip -r /tmp/admin.zip .
          aws s3 cp /tmp/admin.zip s3://${{ secrets.AWS_S3_BUCKET }}/${{ github.sha }}/admin.zip
      - if: ${{ github.event_name == 'push' && github.ref_name == 'main' }}
        working-directory: ./projects/client/dist
        run: |
          zip -r /tmp/client.zip .
          aws s3 cp /tmp/client.zip s3://${{ secrets.AWS_S3_BUCKET }}/${{ github.sha }}/client.zip

  docker-image:
    if: ${{ github.event_name == 'push' && github.ref_name == 'main' }}
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - uses: docker/metadata-action@v5
        id: meta
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=sha,format=long,prefix=
      - uses: docker/build-push-action@v5
        with:
          context: ./projects/server
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
